console.log("H");
console.log("e");
console.log("l");
console.log("l");
console.log("o");
console.log(" ");
console.log("W");
console.log("o");
console.log("r");
console.log("l");
console.log("d");
console.log("!");
