"""
https://projecteuler.net/problem=2
Even Fibonacci numbers
Problem 2 
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def fibonacci(limit):
	n = [1,2]
	while True:
		s = n[-1] + n[-2]
		if s < limit:
			n.append(s)
		else:
			break
	return n

print(sum(x for x in fibonacci(4000000) if not x%2))
