OBTW
author: Ibrahim Hasan
comment: My first time to write in LOLCODE language it's hilarious
TLDR

HAI 1.2
    I HAS A COUNTER ITZ 0
    I HAS A COUNTER2 ITZ 0
    IM IN YR LOOPY UPPIN YR COUNTER TIL BOTH SAEM COUNTER AN 10
        IM IN YR LOOPO UPPIN YR COUNTER2 TIL BOTH SAEM COUNTER2 AN COUNTER
            VISIBLE "*"
        IM OUTTA YR LOOPO
        VISIBLE ":)"
    IM OUTTA YR LOOPY
    VISIBLE "HAI, WORLD!!!1!~"
KTHXBYE
