version: "3.5"
services:
  lucee-helloworld:
    build:
      context: ./lucee
      dockerfile: Dockerfile
    restart: always
    container_name: helloworld-lucee
    ports:
      - "8888:8888" # for multiple instances change 32770 to another port number
