version: '3'
services:
db:
  image: mysql
  ports:
    - "3306:3306"
  volumes:
    - ./var/mysql:/var/lib/mysql
  environment:
    - MYSQL_DATABASE=db
    - MYSQL_USER=admin
    - MYSQL_PASSWORD=password
    - MYSQL_ROOT_PASSWORD=password

web:
  # image: eboraas/apache-php
  image: tutum/apache-php
  ports:
    - "80:80"
    - "443:443"
  links:
    - db
  volumes:
    - ./www:/app
