#!/usr/bin/python

import sys, socket

if len(sys.argv) != 3:
    print "Usage " + sys.argv[0] + " <HOST> <PORT>"
    sys.exit()

buffer = ["A"]
counter = 100

while len(buffer) <=30:
    buffer.append("A" * counter)
    counter = counter + 200

end = "\r\n"

for string in buffer:
    print "Fuzzing with %s bytes" % len(string)
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    s.connect((sys.argv[1], int(sys.argv[2])))
    s.send(string)
    s.recv(1024)
    s.close
    print "Sent\n"
