print("hello Rockies fans")
print("that was a rough Rocktober")
print("while we might loose players as free agents this offseason")
print("we at least showed Nolan why being a Rockie might be great")
print("going to the postseason showed him we can win")
print("this might have sealed our chances of having the best third baseman of all time be a Rockie for life")
print("and that is a win in my book")
print("even if we only scored 2 runs in 28 innings")
print("we will be even better next year!!!")
print("here's to 2019!!")
